services:
  # Backend API service
  - type: web
    name: tempemail-api
    env: node
    buildCommand: npm install
    startCommand: node server/proxy.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # Frontend static site
  - type: web
    name: tempemail-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_PRODUCTION_API_URL
        value: https://tempemail-api.onrender.com/api
      - key: NODE_ENV
        value: production
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: public, max-age=0, must-revalidate 