services:
  # Backend API service
  - type: web
    name: tempemail-api
    env: node
    buildCommand: npm install
    startCommand: node server/proxy.js
    envVars:
      - key: NODE_ENV
        value: production

  # Frontend static site (free tier)
  - type: static
    name: tempemail-frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_PRODUCTION_API_URL
        value: https://tempemail-api.onrender.com/api
      - key: NODE_ENV
        value: production 